### ISSUE TITLE
Field defines a relation with the model 'auth.User', which has been swapped out.

### ISSUE THREAD

**Issue by nikola-milev** [maycuatroi/django-firebase-auth#7]
https://github.com/maycuatroi/django-firebase-auth/blob/58c27292d2c29581674ce384660bac0533e3345b/abstract_auth/abstract_user_profile.py#L9

```python
from django.conf import settings
user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="auth_profile"
 )
```

**Comment by eracle** [comment]
https://github.com/iosifnicolae2/django-firebase-auth/commit/42c19f5b79cb737323e949a10de6143a16c3428b

**Comment by nikola-milev** [comment]
> [iosifnicolae2@42c19f5](https://github.com/iosifnicolae2/django-firebase-auth/commit/42c19f5b79cb737323e949a10de6143a16c3428b)
> 
> Use this in your requirements: git+https://github.com/iosifnicolae2/django-firebase-auth.git@42c19f5

@eracle @iosifnicolae2 some credits for this would be nice :)

**Comment by maycuatroi** [comment]
Resolved in commit https://github.com/maycuatroi/django-firebase-auth/commit/9a5b2478f48a572dbf4da53f413efa8ec7c29e40
